# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Matias Lujan
title: Software Developer
#email: matias.exe.lujan@gmail.com
# email_title: Email (Email title override)
#phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: matiaslujan.vercel.app
website_title: #Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jekyllrb
github_username:  yacardev
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: matiasexelujan
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ


# Additional icon links
additional_links:
- title: Abrir Curriculum Vitae
  icon: fas fa-file-pdf
  url: yacardev.github.io/src/CV_Matias_Lujan_ESP.pdf

additional_links_eng:
- title_eng: Open CV
  icon_eng: fas fa-file-pdf
  url_eng: yacardev.github.io/src/CV_Matias_Lujan_ENG.pdf

language: language

#- title_eng: Open CV
#  icon_eng: fas fa-file-pdf
#  url_eng: yacardev.github.io/src/CV_Matias_Lujan_2023_EN.pdf 
#- title_eng: Español
#  icon_eng: fas fa-solid fa-globe
#  url_eng: localhost:4000 

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
gtm: "GTM-N2898W6"
gtag: "G-VQETK93959"
google_analytics: "G-VQETK93959"

# About Section ESP
about_title: Acerca de Mí
about_profile_image: images/profile/profile-pic.JPG
about_content: | # this will include new lines to allow paragraphs
  Licenciado en Sistemas de Información.

  Mayormente me desempeñé como Software Developer en el ERP Oracle E-Business en sus versiones R11, R12, ERP Cloud en donde obtuve experiencia en la realización de procesos 
  a medida analizando las necesidades del cliente/usuario y utilizando el stack para aplicaciones 
  Oracle. 

  Además de la programación backend me interesa la arquitectura e infraestructura de aplicaciones.
  
  Actualmente ejercitando Java Spring Boot. Realicé cursos de NodeJS con el framework Express.

  
# About Section EN
about_title_eng: About Me
about_profile_image: images/profile/profile-pic.JPG
about_content_eng: | # this will include new lines to allow paragraphs
  Computer Science Degreed.

  I have been working as a ERP Oracle E-Business Software Developer since 2010. 

  I have experience in both R12 and Cloud versions. During this time I have been developing and maintaining new and existing Oracle based applications such us concurrent request processes, OAF pages, configurations, personalizations, performance and so on which were defined to meet customers requirements and necessities.
  
  Furthermore, I am not only interested in Oracle's technologies stack. Consequently, I am a self-learning of Java Spring boot. 
  
  I prefer to be in touch with the backend development.

# Footer
footer_show_references: true
layout: text
references_title: Template by <a href="https://jekyllrb.com" target = "_blank">jekyllrb</a> - Hosted by <a href="https://github.com" target = "_blank">GitHub Pages</a>

#Spanish Page
content:
  #- title: Projects # Title for the section
  #  layout: list # Type of content section (list/text)
  #  content:
  #    - layout: left
  #      border: weak  # Value of `weak` will display a weak border below this item. # Any 
  #                    # other value (or no value) means no border will be displayed
  #      title: Project name
  #      link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #      link_text: Link Text
  #      additional_links:
  #        - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #          icon: fab fa-github
  #          url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #        - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #          icon: fab fa-github
  #          url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #      quote: >
  #        Short overview of the project (optional)
  #      description: | # this will include new lines to allow paragraphs
  #        Description about the work on/with the project
  - title: Experiencia
    layout: list
    content:
      - layout: left
        title: Despegar
        sub_title: Software Developer
        caption: Junio 2022 / Actual
        link: www.despegar.com
        #quote: >
        #  Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Oracle E-Business Suite Software Developer

          - Stack de tecnologías: PL/SQL, Reports, Forms, JDeveloper, OAF Java Framework, Bi Publisher, entre otras
          - Administracion del bot Automation Anywhere 360
          
      - layout: left
        title: OSDE
        sub_title: Technical Owner <p>Software Developer</p>      
        caption: Octubre 2021 - Junio 2022
        link: www.osde.com.ar
        #quote: >
          
        description: | # this will include new lines to allow paragraphs
          Me desempeñe como Technical Owner del producto Gestiones on-line utilizado por los socios de la obra social. 
          Entre otras cosas realicé tareas de coordinación del equipo técnico en la evolución y mantenimiento del producto, 
          priorización de la demanda técnica, nexo con otros equipos de los cuales se requirió colaboración, 
          diseño técnico de la solución en base a los requerimientos funcionales, coordinación de las implementaciones del producto.
          
          
          - SCRUM como metodología ágil de trabajo
          - GitLab, CI/CD          
          - SQL Server
          - Frontend: HTML, CSS, JavaScript y .NET en servidores IIS 
          - Backend: servicios con Java 8, JPA, JAX-RS, JAX-WS. Maven como gestor de Proyectos. Servidores Jboss

      - layout: left
        title: Witbor Argentina S.R.L
        sub_title: Software Developer
        caption: Octubre 2020 / Septiembre 2021
        link: www.witbor.com
        #quote: >
        #  Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Oracle E-Business Suite Technical Consulting
          
          Estuve asignado a los clientes: Adecoagro, Red Link, TyC Sports, TATA (UY), WOM (Colombia) En su mayoría con la versión Oracle ERP Cloud
          
          - Soporte técnico en las distintas mesas de ayuda
          
          - Desarrollo de reportes con OTBI/OBIEE Cloud. Analytics, Dashboards, Infolets, Reports
      - layout: left
        title: ExtendIT Consulting
        sub_title: Software Developer
        caption: Junio 2020 / Octubre 2020
        link: www.extendit.com
        #quote: >
        #  Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Oracle E-Business Suite Technical Consulting
          
          - Asignado al cliente Newsan S.A en proyecto de integración para los módulos AP/Comex entre la herramienta FUSE y el sistema de Aduana SIDOM
      - layout: left
        title: Garbarino S.A
        sub_title: Software Developer
        caption: Junio 2017 / Mayo 2020
        link: www.garbarino.com
        #quote: >
        #  Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Oracle E-Business Suite Software Developer
          
          - Staff interno del equipo de desarrollo para la aplicación Oracle E-Business Suite R-12
      - layout: left
        title: Axon Group Consulting
        sub_title: Software Developer
        caption: Octubre 2014 / Mayo 2017
        #link: www.garbarino.com
        #quote: >
        #  Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Oracle E-Business Suite Technical Consulting
          
          - Asignación full-time al equipo de desarrollo de Oracle E-Business Suite en el cliente Garbarino S.A
      - layout: left
        title: Oracle Consulting Argentina
        sub_title: Software Developer
        caption: Diciembre 2010 / Septiembre 2014
        link: www.oracle.com
        #quote: >
        #  Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Staff Developer Oracle E-Business Suite
          
          - Algunos de los clientes en los que estuve asignado: PepsiCo, Mc Donald’s (Arcos Dorados), Garbarino SA, Cablevisión, Bodegas Salentein, ArPOV, Sherwin Williams, DirecTV, Despegar.com (Argentina y Uruguay), NexTel, Air Liquide
      - layout: left
        title: Freelancer
        sub_title: Web Developer
        caption: 2009 / 2010
        #link: www.oracle.com
        #quote: >
        #  Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Proyecto: “INTA - DBGermoWeb”
          
          - Aplicación para la documentación de recursos genéticos vegetales
          
          - Desarrollo de módulos del sistema utilizando HTML, PHP5, JavaScript, CSS, MySQL
  - title: Educación
    layout: list
    content:
      - layout: left
        title: Universidad Nacional del Nordeste
        sub_title: UNNE. Corrientes, Argentina
        caption: 2003 - 2010
        link: exa.unne.edu.ar
        #quote: >
        #  Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Licenciatura en Sistemas de Información

          Recibido
      - layout: left
        title: Curso de Inglés
        sub_title: Centro Universitario de Idiomas
        link: cui.edu.ar/idioma.php?id=12
        caption: 
        #quote: >
        #  Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Aprobado ciclo de Perfeccionamiento (B2+)
    
  - title: Habilidades
    layout: text
    content: | #
      - Programación
        
        - Laboral en
          - PL/SQL
          - Oracle Reports
          - OAF Java Framework
          - Oracle APEX
          - BI Publisher
          - SQL Oracle, MySQL
          - Oracle Cloud: OTBI/OBIEE. Analytics, Dashboards, Infolets, Reports
          - Oracle E-Business Suite R11-R12 
            - Interfaces
            - APIs
            - Procesos concurrentes
            - Customizaciones
            - Configuraciones
            - Unix commands 
          - Autodidacta en
            - Java Spring boot. NodeJS-Express

      - IDEs/Tools
         - Git. SVN
         - Postman
         - SoapUI
         - SQLDeveloper
         - IntelliJ
         - Visual Studio Code
         - Tickets. JIRA
         - Power BI
      
      - Idiomas
         - Español: Nativo
         - Inglés
           - Lectura/Comprensión: alta
           - Escritura: media
           - Diálogo: media

#English Page
content_eng:
  - title: Experience
    layout: list
    content_eng:
      - layout: left
        title: Despegar
        sub_title: Software Developer
        caption: June 2022 / Actual
        link: www.despegar.com
        description: | # this will include new lines to allow paragraphs
          Oracle E-Business Suite Software Developer

          - SR EBS Developer: PL/SQL, Reports, Forms, JDeveloper, OAF Java Framework, Bi Publisher
          - EBS R12.1.3
          - Administration tasks on VMs that execute the Automation Anywhere 360 bot

      - layout: left
        title: OSDE
        sub_title: Technical Owner <p>Software Developer</p>      
        caption: October 2021 - June 2022
        link: www.osde.com.ar
        #quote: >
          
        description: | # this will include new lines to allow paragraphs
          - Worked with SCRUM methodologic. 
          - Git. CI/CD Implementation
          - Technology stack: 
            - Frontend .NET with IIS servers 
            - Backend services in Java 8, JPA, JAX-RS,  JAX-WS. Maven. JBOSS servers. MS SQL Server data base
          
      - layout: left
        title: Witbor Argentina S.R.L
        sub_title: Software Developer
        caption: October 2020 / September 2021
        link: www.witbor.com
        #quote: >
        #  Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Oracle E-Business Suite Technical Consulting
          
          - I worked in different clients as: Adecoagro, Red Link, TyC Sports, TATA (UY), WOM (Colombia)
          - Mostly with Oracle ERP Cloud and R12.2. 
          - PL/SQL, Reports, Forms, JDeveloper, OAF Java Framework, Bi Publisher
          - OTBI/OBIEE Cloud. Analytics, Dashboards, Infolets, Reports

      - layout: left
        title: ExtendIT Consulting
        sub_title: Software Developer
        caption: June 2020 / October 2020
        link: www.extendit.com
        #quote: >
        #  Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Oracle E-Business Suite Technical Consulting
          
          - I worked for the client: Newsan S.A. 
          - Project: integration between AP/Comex modules to FUSE and SIDOM external applications

      - layout: left
        title: Garbarino S.A
        sub_title: Software Developer
        caption: June 2017 / May 2020
        link: www.garbarino.com
        #quote: >
        #  Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Oracle E-Business Suite Software Developer
          
          - Staff Oracle E-Business Suite Developer.
          - R12.1.3
          - PL/SQL, Reports, Forms, JDeveloper, OAF Java Framework, Bi Publisher, Oracle Apex

      - layout: left
        title: Axon Group Consulting
        sub_title: Software Developer
        caption: October 2014 / May 2017
        #link: www.garbarino.com
        #quote: >
        #  Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Oracle E-Business Suite Software Developer
          
          - Staff Oracle E-Business Suite Developer
          - R-12.1.3. Client: Garbarino S.A
          - PL/SQL, Reports, Forms, JDeveloper, OAF Java Framework, Bi Publisher

      - layout: left
        title: Oracle Consulting Argentina
        sub_title: Software Developer
        caption: December 2010 / September 2014
        link: www.oracle.com
        #quote: >
        #  Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Staff Oracle E-Business Suite Software Developer
          
          - Staff Oracle E-Business Suite Developer
          - Mostly worked in R-12.1.3
          - Clients: PepsiCo, Mc Donald's (Arcos Dorados), Garbarino SA, Cablevisión, Bodegas Salentein, ArPOV, Sherwin Williams, DirecTV, Despegar.com, NexTel, Air Liquide
  
  - title: Education
    layout: list
    content_eng:
      - layout: left
        title: University
        sub_title: Universidad Nacional del Nordeste. Corrientes, Argentina
        caption: 2003 - 2010
        link: exa.unne.edu.ar
        #quote: >
        #  Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Computer Science

          Degreed
      - layout: left
        title: English course
        sub_title: Centro Universitario de Idiomas
        link: cui.edu.ar/idioma.php?id=12
        caption: 
        #quote: >
        #  Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Completed B2+ level
  
  - title: Skills
    layout: text
    content_eng: | #
      - Programming languagues
        
        - Work experience
          - PL/SQL
          - Oracle Reports
          - OAF Java Framework
          - Oracle APEX
          - BI Publisher
          - SQL Oracle, MySQL
          - Oracle Cloud: OTBI/OBIEE. Analytics, Dashboards, Infolets, Reports
          - Oracle E-Business Suite R11-R12 
            - Interfaces
            - APIs
            - Concurrent Programs
            - Personalizations
            - Configurations
            - Unix commands 
          - Self-learning
            - Java Spring boot. NodeJS-Express

      - IDEs/Tools
         - Git. SVN
         - Postman
         - SoapUI
         - SQLDeveloper
         - IntelliJ
         - Visual Studio Code
         - Tickets. JIRA
         - Power BI
      
      - Languages
         - Spanish: Native
         - English
           - Reading/comprehension: Proficient
           - Writing: Intermediate
           - Speaking: Intermediate

# Build settings
 #theme: modern-resume-theme (Use this is you are hosting your resume yourself)
 #remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]